### PR TITLE
Added Danish stop words

### PR DESCRIPTION
**Pull request by dnohr**
Hi guys,

I have just added some danish stop words and sorted the language arrays alphabetically, please review it.

Thanks.

### CODE REVIEW

**Comment by dnohr** [comment]
@michaeldelorenzo How fast will this update reach npm package manager? I'm in need of this update for a projects. Thanks.

**Comment by michaeldelorenzo** [comment]
I'll push an update to npm today.

On Sunday, June 12, 2016, dnohr <notifications@github.com> wrote:

> @michaeldelorenzo <https://github.com/michaeldelorenzo> How fast will
> this update reach npm package manager? I'm in need of this update for a
> projects. Thanks.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/michaeldelorenzo/keyword-extractor/pull/21#issuecomment-225471965>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIK6SWhyFysmLtvM56-oLGMkcHZgY72ks5qLK9cgaJpZM4IzyuJ>
> .
>


-- 
Michael De Lorenzo
michael@delorenzodesign.com | 973.632.7407

**Comment by dnohr** [comment]
Hi @michaeldelorenzo, any news regarding NPM? I still can't download the update. Thanks.

**Comment by michaeldelorenzo** [comment]
Hey @dnohr, sorry about that! Version 0.0.13 is now available on NPM. 

https://www.npmjs.com/package/keyword-extractor

**Pull request merged**
